var mongoose = require('mongoose');


  // TOUR NAME
  // TOUR PHOTOS [ARRAY]
  // TOUR DESCRIPTION
  // TOUR PRICE [ARRAY]
  // DURATION
  // SEASON
  // AVAILABLE DAYS
  // DEPARTURES
  // TOUR-ID
  // GUIDANCE
  // ADDITIONAL INFORMATION
  // INCLUDED [ARRAY]
